### ISSUE TITLE
error while visiting site

### ISSUE THREAD

**Issue by kr-abhi55** [marcobiedermann/weather-app#868]
![Peek 2023-06-09 20-33](https://github.com/marcobiedermann/weather-app/assets/118665057/9e4a5a1b-9405-4cb7-8d0c-fc11f97b3ea2)

**Comment by marcobiedermann** [comment]
@kr-abhi55 

Thank you very much for reporting.
I just fixed this in https://github.com/marcobiedermann/weather-app/pull/872

Note that I've started this app just for fun and haven't touched it in quite a while. Therefore it is lacking some styling which I will address soon … I hope 😄
